### ISSUE TITLE
Match.content() returns owner tag name if content contains newlines

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOX#116]
```
XML = 
  <x>a
  b
  c</x>

$(doc).find("x").content() returns a string including <x>..</x>. When it should return only a b c. It works like this:

XML = 
  <x>a b c</x>

$(doc).find("x").content() returns a b c
```

**Comment by retrohunter** [comment]
I'm now encountering this issue. Is there a workaround?

running 1.3.0

**Comment by retrohunter** [comment]
I may have found the culprit but cannot fork to test due to limitations with my work environment. The regular expression may require the Pattern.DOTALL flag "(?s)". Can someone test?

In Imp on line #~1454: 
```java
private final String content(Element element)
return Util.toString(element).replaceAll("(?s)^<" + name + "(?:[^>]*)>(.*)</" + name + ">$", "$1");
```

**Comment by retrohunter** [comment]
Just created a pull request with the change. (fyi, this hasn't been tested)

**Comment by MartyTremblay** [comment]
Short of being able to build and test, I tried this.
http://fiddle.re/ncumd6 - (http://www.regexplanet.com)

**Comment by lukaseder** [comment]
THanks a lot for your feedback. Will have a look by tomorrow

**Comment by lukaseder** [comment]
Spot on. Your suggestion fixes this issue. Thanks a lot for looking into this

**Comment by MartyTremblay** [comment]
Woot! Thank you for being expeditious. I will test later today.

**Comment by MartyTremblay** [comment]
I'm afraid that there is still a problem :confused:. Although your unit test works, I'm getting strange results with my real-world doc. I'll try to provide you with an example but I'm required to cleanse the doc before posting it. stay tuned.
