### ISSUE TITLE
Util.importOrDetach() throws NPE if element belongs to document and is already detached

### ISSUE THREAD

**Issue by paolofulgoni** [jOOQ/jOOX#131]
Methods which add new content to the DOM (after, append, before, etc.) internally call `Util.importOrDetach(Document document, Element...)`.
If one of the elements to be added belongs to the document and is already detached, the following line throws a `NullPointerException`:

    detached.add((Element) e.getParentNode().removeChild(e));

Stack trace:

	Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
		at org.joox.Util.importOrDetach(Util.java:218)
		at org.joox.Impl.append(Impl.java:1255)
		at org.joox.Impl.append(Impl.java:1248)
		at org.joox.Impl.append(Impl.java:100)

I'm using jOOX 1.2.0.

**Comment by lukaseder** [comment]
Thanks for reporting. Can you provide a full test case? That will make it easier to fix this issue...

**Comment by paolofulgoni** [comment]
Here it is:

    Document document = $().document();
    Element htmlEl = document.createElement("html");
    $(document).append(htmlEl);

**Comment by lukaseder** [comment]
Thanks

**Comment by lukaseder** [comment]
This now works:

```java
    @Test
    public void testAppendDetached() {
        Document document = $("<a/>").document();
        Element e = document.createElement("e");
        $(document).append(e);
        assertEquals("<a><e/></a>", $(document).toString());
    }
```

Currently, jOOX cannot seem to work with a document without root element...

**Comment by paolofulgoni** [comment]
Great, thank you for the fix!
