### ISSUE TITLE
Remove IDE-related files

### ISSUE THREAD

**Issue by paolofulgoni** [jOOQ/jOOX#134]
I think both Eclipse and IntelliJ IDEA can open the project from the Maven configuration file.
So, probably, IDE-related files (e.g `\.settings`, `.classpath`, etc) could be safely removed.

Those files may "interfere" with personal settings etc.

**Comment by lukaseder** [comment]
I might agree on the `.classpath`, but we use the `.settings` for things like code style, file templates (including headers), etc... The settings shouldn't "interfere" with personal settings, as the project settings should always override the personal ones.

Unfortunately, I don't think there's a good solution for keeping the settings "somewhere". I'm open to suggestions, but I want to keep the settings somewhere.

**Comment by paolofulgoni** [comment]
I understand your point. Actually, I also don't know any better solution.

[EditorConfig](http://editorconfig.org/) is a good attempt to standardize code style information, but it lacks too much important settings for Java code. And it seems to be not supported by Eclipse.

**Comment by lukaseder** [comment]
So, what are the problems you're experiencing? Do you get a diff because your Eclipse installation modifies those files?

**Comment by paolofulgoni** [comment]
Actually, I'm not experiencing any problem.
My IDE of choice is IntelliJ IDEA, which ignores all those files (I opened the project from pom.xml).
The code style settings, for example, are not imported. IDEA is able to import code style settings from Eclipse in XML format, which is not included in `\.settings`.

I proposed the cleanup because I thought that those files could be re-created by the IDE, starting from `pom.xml`. I didn't think that actually they're useful to you (and to those using Eclipse).
Sorry for wasting your time, please ignore my proposal (except for `.classpath` if you think it can be safely removed).

**Comment by lukaseder** [comment]
No worries, then :)

I guess we'll leave things as they are. This project doesn't have tons of contributors, so this issue doesn't need to be properly addressed right now.
