### ISSUE TITLE
Improper Restriction of XML External Entity References ('XXE') in XMLasDOMBinding

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOX#136]
See: https://github.com/jOOQ/jOOQ/issues/4592

**Comment by CiaranMcHugh** [comment]
Hi there,

Could this change be released prior to 1.4.0, in 1.3.1 perhaps?

**Comment by lukaseder** [comment]
Hi @CiaranMcHugh: Yes we could, but I suspect that it won't be in the next 2 weeks, as we're rather busy with an upcoming jOOQ release. I'll take a note, though.

**Comment by CiaranMcHugh** [comment]
Thank you very much @lukaseder!

**Comment by lukaseder** [comment]
@CiaranMcHugh: I've just gone ahead and released [version 1.4.0](https://github.com/jOOQ/jOOX/issues?q=milestone%3A%22Version+1.4.0%22+is%3Aclosed+label%3A%22R%3A+fixed%22). There isn't much risk for regressions with only two new added features.

It will hit Maven Central within the next 2-3 hours.

**Comment by CiaranMcHugh** [comment]
Many thanks @lukaseder!
