### ISSUE TITLE
Can't use @XmlJavaTypeAdapter

### ISSUE THREAD

**Issue by pjean** [jOOQ/jOOX#142]
I need to deserialize a string to a LocalDateTime with jaxb and I use @XmlJavaTypeAdapter for that.
But when, I use unmarshalOne the adapter is never call.
Do we have another way for providing a custom conversion ?

**Comment by lukaseder** [comment]
Hmm, from a high level, I would say that should work. Do you have a short test-case to reproduce this?

**Comment by pjean** [comment]
I hadded a short test-case in joox project that I cloned and it's working fine. I need to investigate more my project.
Sorry for the inconvenience.

**Comment by lukaseder** [comment]
No worries :)
