### ISSUE TITLE
UnsupportedOperationException on Android when calling DocumentBuilderFactory.setXIncludeAware()

### ISSUE THREAD

**Issue by notsyncing** [jOOQ/jOOX#149]
When executing simpliest `$("<test></test>")` on android:

```
java.lang.UnsupportedOperationException: This parser does not support specification "Unknown" version "0.0"
   at javax.xml.parsers.DocumentBuilderFactory.setXIncludeAware(DocumentBuilderFactory.java:471)
   at org.joox.JOOX.builder(JOOX.java:943)
   at org.joox.JOOX.$(JOOX.java:238) 
```

Lines in JOOX.java:

```java
factory.setXIncludeAware(false);          // --- Crash at here
factory.setExpandEntityReferences(false);
factory.setNamespaceAware(true);
DocumentBuilder builder = factory.newDocumentBuilder();
```

From android source, it seems this line will always throw:

```java
public void setXIncludeAware(final boolean state) {
    throw new UnsupportedOperationException(
        "This parser does not support specification \""
        + this.getClass().getPackage().getSpecificationTitle()
        + "\" version \""
        + this.getClass().getPackage().getSpecificationVersion()
        + "\""
        );
}
```

So could we just comment this line out or ignore this exception when on android?

joox version 1.4.0, android sdk 25

**Comment by lukaseder** [comment]
Thank you very much for reporting this. Sure, we can exclude this call from being done on Android, or in other words, just catch the exception and ignore it.

The call is being made in the context of a security measurement (#136), and not essential to jOOX's functionality.

We'll release the next version soon, if you're interested in building jOOX from GitHub and providing further feedback on Android usage, that would be greatly appreciated!
