### ISSUE TITLE
jOOX version 1.6.1 not available from maven central

### ISSUE THREAD

**Issue by PascalSchumacher** [jOOQ/jOOX#161]
Version `1.6.1` was not released to maven central.

Due to the incorrect module info in `1.6.0` Eclipse displays all jOOX types as not accessible when you use Java 11 (e.g. `The type org.joox.JOOX is not accessible'). Therefore code completion, automatic imports etc. do not work.

By the way: Thank you very much for providing jOOX!

**Comment by lukaseder** [comment]
Interesting, thanks for the pointer. The tag is there but the milestone hasn't been closed nor has any version been released to Maven Central, indeed. I wonder what went wrong at the time.

I'll try again.

**Comment by lukaseder** [comment]
Heh, in fact, jOOX doesn't currently build with JDK 11. Perhaps that's why the release was interrupted.

**Comment by lukaseder** [comment]
Deploying to Maven Central now... Please wait for another 1-2h for this to be available. Thanks again for reporting!

**Comment by lukaseder** [comment]
> Due to the incorrect module info in 1.6.0 Eclipse displays all jOOX types as not accessible when you use Java 11 (e.g. `The type org.joox.JOOX is not accessible'). Therefore code completion, automatic imports etc. do not work.

Notice, you can always use the joox-java-6 artifact to work around modularity problems. There's only very little difference between the artifacts...

**Comment by PascalSchumacher** [comment]
Now everything works fine. 😃 

Thank you very much!
