### ISSUE TITLE
jaxb-api dependency shouldn't be included for joox-java-6

### ISSUE THREAD

**Issue by stachenov** [jOOQ/jOOX#164]
Built a WAR, deployed to Tomcat 7 running under Java 8, got an error about Java 9 bytecode. The issue is that joox-java-6:1.6.0 depends on jaxb-api:2.3.0, which is Java 9 and later only. Adding an exclusion in my pom.xml fixed the problem, but should the dependency be there in the first place?

**Comment by lukaseder** [comment]
Thank you very much for your report. Indeed, there should be no dependency at all in the Java 6 build. Strange that you would see a dependency on version 2.3.0, though. I get one on 2.2.12:

```
$ mvn dependency:tree

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ joox-java-6 ---
[INFO] org.jooq:joox-java-6:bundle:1.6.1
[INFO] +- javax.xml.bind:jaxb-api:jar:2.2.12:compile
[INFO] +- org.glassfish.jaxb:jaxb-runtime:jar:2.4.0-b180830.0438:provided
[INFO] |  +- org.glassfish.jaxb:txw2:jar:2.4.0-b180830.0438:provided
[INFO] |  +- com.sun.istack:istack-commons-runtime:jar:3.0.7:provided
[INFO] |  +- org.jvnet.staxex:stax-ex:jar:1.8:provided
[INFO] |  +- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:provided
[INFO] |  \- javax.activation:javax.activation-api:jar:1.2.0:provided
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- commons-io:commons-io:jar:2.4:test
[INFO] \- xalan:xalan:jar:2.7.2:test
[INFO]    \- xalan:serializer:jar:2.7.2:test
[INFO]       \- xml-apis:xml-apis:jar:1.3.04:test
```

**Comment by lukaseder** [comment]
Fixed for jOOX 1.6.2

**Comment by stachenov** [comment]
Just to be clear: 1.6.0 has a dependency on 2.3.0, 1.6.1 on 2.2.12. Figures. Doesn't matter now that it is fixed, though.

**Comment by lukaseder** [comment]
Version 1.6.2 has been released including a fix for this issue. It will be available from Maven Central shortly.
