### ISSUE TITLE
JOOX.$ should add an overload accepting a Path object

### ISSUE THREAD

**Issue by helpermethod** [jOOQ/jOOX#165]
### Expected behavior and actual behavior:

Most modern Java APIs return objects of type `Path` or `Stream<Path>`. Having to convert every `Path` object to a `File` using `path.toFile()` seems tedious and unnecessary.

Because JOOX.$ already has quite a few overloads, another overload accepting a Path object wouldn't hurt.

### Steps to reproduce the problem:

    Joox.$(Path.of("/home/helpermethod")); // seems to work but selects the wrong overload

### Versions:

- jOOX: 1.6.0
- Java: 8

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I agree this could be done
