### ISSUE TITLE
Javadoc 1.6.0 at https://www.jooq.org/products/jOOX/javadoc/latest has no classes listed!

### ISSUE THREAD

**Issue by rwperrott** [jOOQ/jOOX#171]
I expected to see several classes listed, but saw none at the above URL!

- jOOX: 1.6.0
- Java: NA

**Comment by lukaseder** [comment]
Thanks for your report. Clicking through a few links, it seems that everything works as expected?
https://www.jooq.org/products/jOOX/javadoc/1.6.0/allclasses-noframe.html

**Comment by rwperrott** [comment]
My route was https://www.jooq.org/products/jOOX/javadoc/1.6.0/overview-summary.html then
https://www.jooq.org/products/jOOX/javadoc/1.6.0/org.jooq.joox-summary.html, which seems to be no-frames and useless, and I only saw something useful when I clicked on frames, or _your link_, so it looks like some unhelpful and confusing design in the Javadoc tool for module Javadocs.

**Comment by lukaseder** [comment]
I think that's the JDK's default behaviour for single package modules? Not sure if much can be done about it...

**Comment by lukaseder** [comment]
Hm, it's indeed different from the others, including these:

- https://www.jooq.org/products/jOOU/javadoc/0.9.4/org.jooq.joou-summary.html
- https://www.jooq.org/products/jOOR/javadoc/0.9.10/org.jooq.joor/module-summary.html

Seems to be related to the specific JDK version that was used to build the Javadoc, at the time. Will investigate.

**Comment by lukaseder** [comment]
Also, the latest version is 1.6.3...

**Comment by lukaseder** [comment]
Now it's better. Thanks again for your report.

**Comment by lukaseder** [comment]
(You may need to delete your browser cache for the HTTP redirect from latest to 1.6.3 to work)
