### ISSUE TITLE
Support `Optional<T>` as return type for accessor

### ISSUE THREAD

**Issue by faustin0** [jOOQ/jOOX#191]
Hi, thanks for your work, i'm using the library in a project with java > 8 and what i feel is missing is that the accessors like .attr("name") returns `null` instead of a more friendly Optional<T>.
So something like:  
`Optional<String> optAttr(String name);`
This will be very helpful to avoid many null checks and chain common mapping operations.
Another helpful method could be the 
`Optional<String> requiredAttr(String name);`
that will enforce a value to be present or throw a detailed exception otherwise.
Is this a design choice ? can those method be added? I can contribute if necessary

**Comment by lukaseder** [comment]
This is just a bikeshed that jOOX prefers not to paint.

Even if it was desirable to go down a route where we'd refactor things to embrace `Optional` (despite its flaws), we wouldn't because it would be a backwards incompatible change.
